/* Golflev strings.js v1 — 文言キー管理（D6: 直書き禁止）
   使い方: STR.t('pitch.intro.body')。言語は golflev:lang（既定 ja） */
const STR = {
  lang: (function(){ try{ return localStorage.getItem('golflev:lang')||'ja'; }catch(e){ return 'ja'; } })(),
  d: {
    'pitch.eyebrow':        { ja:'Level 2 — Drill',            en:'Level 2 — Drill' },
    'pitch.title.jp':       { ja:'ピッチ',                       en:'The Pitch' },
    'pitch.intro.body':     { ja:'8時から、4時へ。<br>アプローチの距離感は、<br>この振り幅の再現性から。', en:'From 8 to 4.<br>Distance control starts with<br>a repeatable swing width.' },
    'pitch.intro.note':     { ja:'両側60°のゾーンに、3回そろえて振る。それが今日の課題です。', en:'Three swings, both sides inside the 60° zone. That is today’s work.' },
    'pitch.btn.begin':      { ja:'はじめる',                     en:'Begin' },

    'sensor.title.jp':      { ja:'センサー',                     en:'The Sensor' },
    'sensor.body':          { ja:'計測にはセンサーの許可が必要です。<br>スマホを縦に、画面を上に向けて握ります。', en:'Sensor access is required.<br>Hold the phone upright, screen facing up.' },
    'sensor.btn':           { ja:'センサーを有効にする',           en:'Enable Sensors' },
    'sensor.denied':        { ja:'許可されませんでした。設定からやり直してください。', en:'Permission denied. Please try again from Settings.' },

    'address.title.jp':     { ja:'アドレス',                     en:'The Address' },
    'address.body':         { ja:'アドレスの構えで、動かずに。',     en:'Take your address. Hold still.' },
    'address.btn':          { ja:'キャリブレーション開始',         en:'Calibrate' },
    'address.hold':         { ja:'そのまま動かない',               en:'Hold still' },
    'address.done':         { ja:'記録完了',                     en:'Recorded' },
    'address.vertical':     { ja:'シャフトが鉛直に近すぎます。通常のアドレスの角度で構え直してください。', en:'Shaft too vertical. Please address at a normal angle.' },

    'live.ready':           { ja:'どうぞ',                       en:'Go.' },
    'live.sub.ready':       { ja:'振ってください',                 en:'Swing through.' },
    'live.sub.waiting':     { ja:'そのまま静止',                  en:'Hold still.' },
    'live.hint':            { ja:'振る間は、ボールを見て。画面は見なくて大丈夫です。', en:'Watch the ball while you swing. No need to look at the screen.' },
    'live.flip':            { ja:'針の向きを反転',                 en:'Flip needle direction' },
    'live.bodyNote':        { ja:'手元の動きを計測しています。全身の姿勢はイメージです。', en:'We measure your hands’ motion — the full-body pose is illustrative.' },
    'live.measuring':       { ja:'計測中',                       en:'Measuring' },
    'live.ball':            { ja:'ボールを見て。',                en:'Eyes on the ball.' },
    'live.replay':          { ja:'いまのスイング',                en:'Your swing' },
    'live.back':            { ja:'バック計測中',                  en:'Backswing' },
    'live.through':         { ja:'フォロー計測中',                en:'Through' },
    'live.swing':           { ja:'スイング',                     en:'Swing' },
    'live.btn.redo':        { ja:'この1球を取り直す',             en:'Redo this swing' },
    'live.btn.recal':       { ja:'較正からやり直す',               en:'Recalibrate' },
    'live.dim.on':          { ja:'スイング集中モード：オン',         en:'Swing-focus: On' },
    'live.dim.off':         { ja:'スイング集中モード：オフ',         en:'Swing-focus: Off' },
    'live.dim.desc':        { ja:'振っている間は画面を暗くします。振り終わってから、3Dで再生します。', en:'The screen dims while you swing, then replays in 3D afterward.' },
    'live.focusHint.title': { ja:'次は、画面を見ずに振ってみませんか。', en:'Next time, try swinging without watching the screen.' },
    'live.focusHint.body':  { ja:'振る間だけ画面を伏せると、目線が上がるクセ（ヘッドアップ）が出にくくなります。振ったスイングは、あとで3Dで見られます。', en:'Dimming the screen while you swing helps prevent looking up (head-up). You can review your swing in 3D afterward.' },
    'live.focusHint.cta':   { ja:'スイング集中モードをためす',       en:'Try Swing-focus mode' },
    'live.focusHint.later': { ja:'あとで',                         en:'Later' },
    'review.title':         { ja:'スイングを、もう一度。',         en:'See it once more.' },
    'review.again':         { ja:'もう一度見る',                  en:'Watch again' },
    'review.close':         { ja:'閉じる',                       en:'Close' },
    'live.redo':            { ja:'取り消しました。構え直してください', en:'Cleared. Re-address.' },
    'live.tooSmall':        { ja:'小さすぎます — もう一度',        en:'Too small — again' },
    'live.chip.ok':         { ja:'良い振り幅',                    en:'Good width' },
    'live.chip.broken':     { ja:'三角形が崩れました',             en:'Triangle broke' },
    'live.chip.decel':      { ja:'緩みました',                    en:'Decelerated' },
    'live.chip.shallow':    { ja:'浅い — もう少し上まで',          en:'Shallow' },
    'live.chip.deep':       { ja:'深い — 8時で止める',            en:'Too deep' },
    'live.chip.noFollow':   { ja:'フォローまで振り切る',           en:'Swing through' },
    'live.return':          { ja:'構えて、止まる',                 en:'Address. Hold.' },
    'live.chip.over':       { ja:'振りかぶり過ぎ — 8時で止める',    en:'Too far back — stop at 8' },

    'result.title.jp':      { ja:'結果',                        en:'The Result' },
    'result.rank.perfect':  { ja:'3球がそろっています',            en:'Three matching swings.' },
    'result.rank.good':     { ja:'よい再現性です',                en:'Good consistency.' },
    'result.rank.almost':   { ja:'も う 少 し',                  en:'Almost.' },
    'result.rank.tryagain': { ja:'も う 一 度',                  en:'Once more.' },
    'result.stat.mean':     { ja:'平均振り幅',                    en:'Avg width' },
    'result.stat.sd':       { ja:'ばらつき',                      en:'Spread' },
    'result.stat.zone':     { ja:'ゾーン内',                      en:'In zone' },
    'result.issues':        { ja:'今日の課題',                    en:'Today’s work' },
    'result.noIssues':      { ja:'指摘はありません。この感覚を繰り返しましょう。', en:'Nothing to fix. Repeat this feeling.' },
    'result.recommend':     { ja:'コーチのおすすめ',               en:'Coach’s pick' },
    'result.issue.elbow':   { ja:'右肘の曲がり',                  en:'Trail elbow bend' },
    'result.issue.decel':   { ja:'インパクトの緩み',               en:'Deceleration' },
    'result.issue.spread':  { ja:'振り幅のばらつき',               en:'Width spread' },
    'result.issue.shallow': { ja:'振り幅が浅い',                  en:'Too shallow' },
    'result.issue.deep':    { ja:'振り幅が深い',                  en:'Too deep' },
    'result.issue.follow':  { ja:'フォロー不足',                  en:'Short follow' },
    'result.focusNote':     { ja:'次のセットで、これだけを意識しましょう。', en:'Focus on this one thing next set.' },
    'result.partial.elbow': { ja:'今回は肘の判定ができませんでした（加速度データ不足）', en:'Elbow check unavailable this set.' },
    'result.btn.again':     { ja:'もう1セット',                  en:'Another set' },
    'result.btn.recal':     { ja:'構え直す',                     en:'Re-address' },

    'home.gap.pre':         { ja:'目標まで',                     en:'To your goal' },
    'home.gap.unit':        { ja:'打 を 削る',                   en:'strokes to shave' },
    'home.gap.best':        { ja:'ベスト',                       en:'Best' },
    'home.gap.target':      { ja:'目標',                         en:'Target' },
    'home.today.label':     { ja:'今日のドリル',                  en:'Today’s drill' },
    'home.today.start':     { ja:'はじめる',                     en:'Begin' },
    'home.today.continue':  { ja:'つづける',                     en:'Continue' },
    'home.today.again':     { ja:'もう1セット',                  en:'One more set' },
    'home.map.label':       { ja:'カリキュラム',                  en:'The Path' },
    'home.map.pro':         { ja:'Pro',                          en:'Pro' },
    'home.lv.locked':       { ja:'ロック中',                     en:'Locked' },
    'home.lv.active':       { ja:'いまここ',                     en:'You are here' },
    'home.lv.done':         { ja:'達成',                         en:'Cleared' },
    'lv0.name.en':          { ja:'The Setup',                    en:'The Setup' },
    'lv0.name.jp':          { ja:'グリップ＆アドレス',             en:'Grip & Address' },

    'grip.entry.eyebrow':   { ja:'Lesson 00',                    en:'Lesson 00' },
    'grip.entry.title':     { ja:'握りから、整える。',             en:'Start with the grip.' },
    'grip.entry.en':        { ja:'The Setup',                    en:'The Setup' },
    'grip.entry.sub':       { ja:'登録は、いりません。まず見るだけ。', en:'No sign-up. Just take a look.' },
    'grip.eyebrow':         { ja:'Lesson 00 — The Setup',         en:'Lesson 00 — The Setup' },
    'grip.title.jp':        { ja:'グリップ',                     en:'The Setup' },
    'grip.title.en':        { ja:'The Setup',                    en:'The Setup' },
    'grip.intro':           { ja:'クラブの握りと、立ち方を整えます。<br>ここでは測りません。お手本を見て、<br>ご自身と見比べてください。', en:'Set your grip and your stance.<br>Nothing is measured here — look at<br>the model and compare yourself.' },
    'grip.part1.no':        { ja:'I',                            en:'I' },
    'grip.part1.label':     { ja:'握り',                         en:'The Grip' },
    'grip.part2.no':        { ja:'II',                           en:'II' },
    'grip.part2.label':     { ja:'立ち方',                       en:'The Stance' },
    'grip.notMeasure':      { ja:'これは測定ではありません。お手本を見て、ご自身の手元と見比べる時間です。', en:'This is not a measurement. It is time to look at the model and compare with your own hands.' },
    'grip.back':            { ja:'ホーム',                       en:'Home' },
    'grip.show.title':      { ja:'基本の握りを、見る。',           en:'See the basic grip.' },
    'grip.show.caption':    { ja:'ゴールドの線が示すのは、握る位置・被せ具合・力の入れ方です。', en:'The gold lines point to grip position, how the knuckles show, and pressure.' },
    'grip.show.modelCap':   { ja:'クラブの握りのお手本です。下の3点と見比べて、ご自身の握りを整えてください。', en:'A model of the club grip. Compare it with the three points below and set your own.' },
    'grip.show.placeholder':{ ja:'お手本の映像を準備中です。',       en:'Model footage coming soon.' },
    'grip.handedness':      { ja:'※ 右打ちの方向けです。左打ちの方は、左右を入れ替えてご覧ください。', en:'For right-handed players. If you play left-handed, reverse left and right.' },
    'grip.check.title':     { ja:'握りを見る、3つのポイント。',     en:'Three points to look at.' },
    'grip.check.1.title':   { ja:'握る位置',                     en:'Where it sits' },
    'grip.check.1.body':    { ja:'左手（前の手）は、指の付け根に斜めに乗せます。手のひらにべったり乗せると、球が散りやすくなります。', en:'Set the lead (left) hand across the base of the fingers. Resting it flat in the palm tends to scatter the ball.' },
    'grip.check.2.title':   { ja:'被せ具合',                     en:'Knuckles shown' },
    'grip.check.2.body':    { ja:'構えたとき、左手の拳が2.5〜3個見えるくらい。1個以下は球が右へ逃げやすく、4個は被せ過ぎの目安です。', en:'At address, about 2.5–3 knuckles of the lead hand show. One or fewer tends to leak right; four is a sign of too strong.' },
    'grip.check.3.title':   { ja:'握る強さ',                     en:'Grip pressure' },
    'grip.check.3.body':    { ja:'10段階で4〜5、小鳥を包むくらい。強く握りすぎると力んで、タイミングがズレやすくなります。', en:'About 4–5 out of 10 — like holding a small bird. Gripping too hard tightens up and tends to throw off timing.' },
    'grip.check.note':      { ja:'どれも目安です。完璧な正解は、ひとつではありません。', en:'These are guidelines — there is no single perfect grip.' },
    'grip.stance.title':    { ja:'立ち方を、見る。',               en:'See the stance.' },
    'grip.stance.sub':      { ja:'ピッチ・アプローチの構え',       en:'The pitch & approach setup' },
    'grip.stance.viewFront':{ ja:'正面から',                     en:'From the front' },
    'grip.stance.viewFoot': { ja:'足元から見た目安',               en:'A guide, seen from the feet' },
    'grip.stance.caption':  { ja:'アドレス（構え）のお手本です。下の目安と見比べて、ご自身の構えを整えてください。', en:'A model of the address posture. Compare it with the guides below and set your own stance.' },
    'grip.stance.s1.l':     { ja:'足幅',                         en:'Stance' },
    'grip.stance.s1.v':     { ja:'こぶし1.5〜2個分。肩幅より、やや狭めが目安です。', en:'About 1.5–2 fists wide — a touch narrower than your shoulders.' },
    'grip.stance.s2.l':     { ja:'体重',                         en:'Weight' },
    'grip.stance.s2.v':     { ja:'やや左足寄り。目安は6：4くらいです。', en:'Slightly onto the lead foot — about 6:4 as a guide.' },
    'grip.stance.s3.l':     { ja:'距離',                         en:'Distance' },
    'grip.stance.s3.v':     { ja:'手元と体の間は、こぶし1〜1.5個分。腕が突っ張れば遠すぎ、窮屈なら近すぎのサインです。', en:'About 1–1.5 fists between your hands and body. Arms reaching out means too far; cramped means too close.' },
    'grip.stance.s4.l':     { ja:'前傾',                         en:'Tilt' },
    'grip.stance.s4.v':     { ja:'背すじを保ったまま、股関節から前へ傾けます。', en:'Tilt forward from the hips while keeping your spine long.' },
    'grip.stance.s5.l':     { ja:'ボール',                       en:'Ball' },
    'grip.stance.s5.v':     { ja:'両足の中央〜半個分右が目安。素振りでは「置くつもり」でイメージします。', en:'Roughly centre to half a ball right of centre. On a practice swing, picture it there.' },
    'grip.stance.note':     { ja:'お手本の一例です（人により変わります）。体重はこのアプリでは測りません。向き（狙いの方向）は、目標のある場所で。', en:'One example model — it varies by person. Weight is not measured in this app. Aim belongs where you have a target.' },
    'grip.cta.bridge':      { ja:'握りが決まったら、振り幅を測る。', en:'Once your grip feels set, measure your swing width.' },
    'grip.cta.title':       { ja:'次は、ピッチへ。',               en:'Next, The Pitch.' },
    'grip.cta.btn':         { ja:'ピッチを測る',                  en:'Measure The Pitch' },
    'grip.cta.home':        { ja:'ホームに戻る',                  en:'Back to Home' },
    'lv1.name.en':          { ja:'The Triangle',                 en:'The Triangle' },
    'lv1.name.jp':          { ja:'三角形テイクバック',             en:'Triangle Takeback' },
    'lv2.name.en':          { ja:'The Pitch',                    en:'The Pitch' },
    'lv2.name.jp':          { ja:'ピッチ',                       en:'Pitch' },
    'lv3.name.en':          { ja:'The Business Zone',            en:'The Business Zone' },
    'lv3.name.jp':          { ja:'ビジネスゾーン',                en:'Business Zone' }
  },
  t(key){
    const e=this.d[key];
    if(!e) return key;
    return e[this.lang]||e.ja;
  }
};
